### ISSUE TITLE
dependency_injector together with requests fails

### ISSUE THREAD

**Issue by herrphon** [ets-labs/python-dependency-injector#165]
Hi,
I'm using the dependency_injector and when I'm doing a `import requests`, I get the following exception:
```
Traceback (most recent call last):
  File "/Users/phon/code/python/anker/lib/main.py", line 19, in <module>
    main()
  File "/Users/phon/code/python/anker/lib/main.py", line 16, in main
    Application.app(cli.command, cli.arguments)
  File "src/dependency_injector/providers.pyx", line 97, in dependency_injector.providers.Provider.__call__ (src/dependency_injector/providers.c:2753)
  File "src/dependency_injector/providers.pyx", line 597, in dependency_injector.providers.Callable._provide (src/dependency_injector/providers.c:9215)
  File "src/dependency_injector/providers.pxd", line 261, in dependency_injector.providers.__callable_call (src/dependency_injector/providers.c:23398)
  File "/Users/phon/code/python/anker/lib/anker/app.py", line 15, in app
    import requests
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/Users/phon/code/python/anker/lib/python3.6/site-packages/urllib3/util/selectors.py", line 15, in <module>
    from demo import my_math
ModuleNotFoundError: No module named 'demo'
```

**Comment by rmk135** [comment]
Hi @herrphon ,

Have just read the initial description on my email... Just wanted to say you that - no problems, you're welcome here with any questions :)

Have a good day,
Roman
