### ISSUE TITLE
Using of configuration provider with some singleton providers

### ISSUE THREAD

**Issue by iskorini** [ets-labs/python-dependency-injector#313]
Hi, I've a problem with wiring function and I don't understand where I'm wrong. 
My classes are that:

ConfigurationContainer.py
```python
from dependency_injector import containers, providers

class ConfigContainer(containers.DeclarativeContainer):
    config = providers.Configuration()
```
DependencyContainer.py
```python
from dependency_injector import containers, providers

from src.DialogflowInteraction import DialogflowInteraction
from src.QA.ContextRetriever.VeryBasicContextRetriever import \
    VeryBasicContextRetriever
from src.QA.QA import QA


class BotDependencyFactory(containers.DeclarativeContainer):
    verybasiccontextretriever = providers.Singleton(VeryBasicContextRetriever)
    q_a = providers.Singleton(QA)
    dialogflowinteraction = providers.Singleton(DialogflowInteraction)
```
Bot.py
```python
import logging
from uuid import uuid1
import sys
from dependency_injector.wiring import Provide

from src.ConfigurationContainer import ConfigContainer
from src.DependencyContainer import BotDependencyFactory



class Bot():
    
    def __init__(
        self, 
        threshold=Provide[ConfigContainer.config.general.threshold.as_float()],
        q_a = Provide[BotDependencyFactory.q_a],
        context_retriever = Provide[BotDependencyFactory.verybasiccontextretriever],
        dialogflowinteraction = Provide[BotDependencyFactory.dialogflowinteraction]
        ):
        self.threshold = threshold
        self.QA = q_a
        self.context_retriever = context_retriever
        self.df_bot = dialogflowinteraction
```
app.py
```python
import logging
import os
import sys

from src.ConfigurationContainer import ConfigContainer
from src.DependencyContainer import BotDependencyFactory
from src.bot import Bot


def configure_env():
    logging.basicConfig(level=logging.INFO)
    config = ConfigContainer()
    config.config.from_ini('config.ini')
    logging.info('configuration completed')
    return config

if __name__ == '__main__':
    config = configure_env()
    config.wire(modules=[sys.modules[__name__]])
    logging.info('Configuration container wired successfully')
    bot_dependency_factory = BotDependencyFactory()
    bot_dependency_factory.wire(modules=[sys.modules[__name__]])
    bot = Bot()    
```
When I try to run main method returns this exception
```
INFO:root:configuration completed
Traceback (most recent call last):
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 111, in _resolve_provider
    return self._map[original]
KeyError: <dependency_injector.providers.Singleton(<class 'src.QA.QA.QA'>) at 0x256758fd630>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/Federico/Desktop/DeepCleverBot/bot/app.py", line 24, in <module>
    config.wire(modules=[sys.modules[__name__]])
  File "src/dependency_injector/containers.pyx", line 195, in dependency_injector.containers.DynamicContainer.wire
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 162, in wire
    _patch_fn(member, method_name, method, providers_map)
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 193, in _patch_fn
    injections = _resolve_injections(fn, providers_map)
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 218, in _resolve_injections
    provider = providers_map.resolve_provider(marker.provider)
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 55, in resolve_provider
    return self._resolve_provider(provider)
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 113, in _resolve_provider
    raise Exception('Unable to resolve original provider')
Exception: Unable to resolve original provider
```

**Comment by rmk135** [comment]
Hi @iskorini. Thanks for opening the issue. Everything seems correct from the first sight. I need to debug this. I'll get back when I have more information.

**Comment by rmk135** [comment]
Hi @iskorini,

This was a bug. The fix is published in version [`4.1.6`](https://python-dependency-injector.ets-labs.org/main/changelog.html) . Upgrade, please.

The use case when same modules are wired to several containers at the same time was not tested. I've added needed tests and implemented needed fixes. My apologies for inconvenience and thanks for reporting the issue.

I'm closing the issue. Feel free to comment, re-open if needed.

Best,
Roman

**Comment by iskorini** [comment]
Hi @rmk135, thank u so much for support.
I've another issue. QA's class constructor requires a string: 
```python
class QA():
    def __init__(self, model=Provide[ConfigContainer.config.model.name]):
        self.model = model
        self.init_model()
```
if I create a new QA object in main method everything goes fine, but using 'BotDependencyFactory' they return this error that is like config wasn't wired: 
```python
INFO:root:configuration completed
INFO:root:Configuration container wired successfully
INFO:root:Initializing model...
INFO:root:model: <dependency_injector.wiring.Provide object at 0x00000235228E4250>
Traceback (most recent call last):
  File "c:/Users/Federico/Desktop/DeepCleverBot/bot/app.py", line 24, in <module>
    bot = Bot()
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 319, in _patched
    to_inject[injection] = provider()
  File "src/dependency_injector/providers.pyx", line 160, in dependency_injector.providers.Provider.__call__
  File "src/dependency_injector/providers.pyx", line 2130, in dependency_injector.providers.Singleton._provide
  File "src/dependency_injector/providers.pxd", line 450, in dependency_injector.providers.__factory_call
  File "src/dependency_injector/providers.pxd", line 436, in dependency_injector.providers.__callable_call
  File "src/dependency_injector/providers.pxd", line 432, in dependency_injector.providers.__call
  File "c:\Users\Federico\Desktop\DeepCleverBot\bot\src\QA\QA.py", line 13, in __init__
    self.init_model()
  File "c:\Users\Federico\Desktop\DeepCleverBot\bot\src\QA\QA.py", line 18, in init_model
    self.tokenizer = BertTokenizer.from_pretrained(self.model, return_token_type_ids = True)
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\transformers\tokenization_utils_base.py", line 1516, in from_pretrained
    if os.path.isfile(pretrained_model_name_or_path) or is_remote_url(pretrained_model_name_or_path):
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Provide
```

**Comment by rmk135** [comment]
Hi @iskorini , can you, please, post a code that causes this error?

**Comment by rmk135** [comment]
I have re-reproduced the issue. Looking for a way to resolve it.

**Comment by rmk135** [comment]
This issue is related to a problem that ``wiring`` does improper multiple importing of the modules when looking for the injection markers. I'll create another issue for this. The fix is coming soon.

**Comment by rmk135** [comment]
@iskorini

Fixed in `4.3.5`. See #320 .

Thanks for reporting the issue. You're welcome to upgrade to a patched version.

**Comment by iskorini** [comment]
@rmk135 Thanks a lot! I've temporarily fix this problem importing `from src.QA.QA import QA` in .py file that cointain main method, even if I don't explicit use in this file. Other classes are unchanged from first message.
```python
import logging
import os
import sys

from src.bot import Bot
from src.ConfigurationContainer import ConfigContainer
from src.DependencyContainer import BotDependencyFactory
############## DON'T TOUCH!!! ##############
from src.QA.QA import QA
############## DON'T TOUCH!!! ##############

def configure_env():
    logging.basicConfig(level=logging.INFO)
    config = ConfigContainer()
    config.config.from_ini('config.ini')
    some_stuff()
    return config

if __name__ == '__main__':
    config = configure_env()
    logging.info('Configuration container wired successfully')
    bot_dependency_factory = BotDependencyFactory()
    bot_dependency_factory.wire(modules=[sys.modules[__name__]])
    config.wire(modules=[sys.modules[__name__]])
    bot = Bot()
```
so I think that the problem is my error in wiring `config`. If in this main method I write `qa = QA()` it works without any problem.

**Comment by rmk135** [comment]
@iskorini ,  so what you should do is wiring of the `QA` package.

```python

from src import QA
...
config.wire(modules=[sys.modules[__name__]], packages=[QA])
```

Or the same, but with a module:

```python

from src.QAimport QA
...
config.wire(modules=[sys.modules[__name__], QA])
```

Injections will not work until you wire the container with needed modules and packages.
