### ISSUE TITLE
Wiring does improper import

### ISSUE THREAD

**Issue by rmk135** [ets-labs/python-dependency-injector#320]
Module ``wiring`` does improper import of modules when looks for injection markers using ``packages=[]`` option. This caused multiple imports of the same module.

Here is user's comment on this:

---

Hi @rmk135, thank u so much for support.
I've another issue. QA's class constructor requires a string: 
```python
class QA():
    def __init__(self, model=Provide[ConfigContainer.config.model.name]):
        self.model = model
        self.init_model()
```
if I create a new QA object in main method everything goes fine, but using 'BotDependencyFactory' they return this error that is like config wasn't wired: 
```python
INFO:root:configuration completed
INFO:root:Configuration container wired successfully
INFO:root:Initializing model...
INFO:root:model: <dependency_injector.wiring.Provide object at 0x00000235228E4250>
Traceback (most recent call last):
  File "c:/Users/Federico/Desktop/DeepCleverBot/bot/app.py", line 24, in <module>
    bot = Bot()
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\dependency_injector\wiring.py", line 319, in _patched
    to_inject[injection] = provider()
  File "src/dependency_injector/providers.pyx", line 160, in dependency_injector.providers.Provider.__call__
  File "src/dependency_injector/providers.pyx", line 2130, in dependency_injector.providers.Singleton._provide
  File "src/dependency_injector/providers.pxd", line 450, in dependency_injector.providers.__factory_call
  File "src/dependency_injector/providers.pxd", line 436, in dependency_injector.providers.__callable_call
  File "src/dependency_injector/providers.pxd", line 432, in dependency_injector.providers.__call
  File "c:\Users\Federico\Desktop\DeepCleverBot\bot\src\QA\QA.py", line 13, in __init__
    self.init_model()
  File "c:\Users\Federico\Desktop\DeepCleverBot\bot\src\QA\QA.py", line 18, in init_model
    self.tokenizer = BertTokenizer.from_pretrained(self.model, return_token_type_ids = True)
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\site-packages\transformers\tokenization_utils_base.py", line 1516, in from_pretrained
    if os.path.isfile(pretrained_model_name_or_path) or is_remote_url(pretrained_model_name_or_path):
  File "C:\Users\Federico\anaconda3\envs\deepcleverbot\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not Provide
```

_Originally posted by @iskorini in https://github.com/ets-labs/python-dependency-injector/issues/313#issuecomment-722357816_

**Comment by rmk135** [comment]
The issue is fixed in `4.3.5`. The release is on PyPI.

@iskorini, thanks for reporting the issue. You're welcome to upgrade to a patched version.
