### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by wackazong** [ets-labs/python-dependency-injector#423]
When my resource provider causes an exception here, it is leaked to ASGI and not handled correcly here it seems:

https://github.com/ets-labs/python-dependency-injector/blob/ee89476db03b0dfaf6dd94d38cd9d8ceedfc4c9f/src/dependency_injector/providers.pyx#L3471

This is my resouce init method

    async def init_redis(url: str) -> AsyncIterator[Redis]:
        pool = await create_redis_pool(url)
        yield pool
        pool.close()
        await pool.wait_closed()

Used like this:

    redis_pool = providers.Resource(init_redis, url=config.redis_url)

Log:

`Traceback (most recent call last):
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/dependency_injector/wiring.py", line 623, in _patched
    async_to_inject = await asyncio.gather(*[provide for _, provide in to_inject_await])
  File "src/dependency_injector/providers.pyx", line 2625, in dependency_injector.providers.BaseSingleton._async_init_instance
  File "src/dependency_injector/providers.pxd", line 578, in dependency_injector.providers.__async_call_callback
  File "src/dependency_injector/providers.pxd", line 470, in dependency_injector.providers.__async_prepare_args_kwargs_callback
  File "src/dependency_injector/providers.pyx", line 776, in dependency_injector.providers.Dependency._async_provide
  File "src/dependency_injector/providers.pyx", line 776, in dependency_injector.providers.Dependency._async_provide
  File "src/dependency_injector/providers.pxd", line 578, in dependency_injector.providers.__async_call_callback
  File "src/dependency_injector/providers.pxd", line 470, in dependency_injector.providers.__async_prepare_args_kwargs_callback
  File "src/dependency_injector/providers.pyx", line 776, in dependency_injector.providers.Dependency._async_provide
  File "src/dependency_injector/providers.pyx", line 3471, in dependency_injector.providers.Resource._async_init_callback
  File "./src/framework/gateways/redis.py", line 6, in init_redis
    pool = await create_redis_pool(url)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/aioredis/commands/__init__.py", line 188, in create_redis_pool
    pool = await create_pool(address, db=db,
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/aioredis/pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/aioredis/connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "/Users/ander/.pyenv/versions/3.8.7/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/Users/ander/Development/Repos/wakeupcall/.venv/lib/python3.8/site-packages/aioredis/stream.py", line 23, in open_connection
    transport, _ = await get_event_loop().create_connection(
  File "/Users/ander/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py", line 986, in create_connection
    infos = await self._ensure_resolved(
  File "/Users/ander/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py", line 1365, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/Users/ander/.pyenv/versions/3.8.7/lib/python3.8/asyncio/base_events.py", line 825, in getaddrinfo
    return await self.run_in_executor(
  File "/Users/ander/.pyenv/versions/3.8.7/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ander/.pyenv/versions/3.8.7/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known`

**Comment by rmk135** [comment]
Thanks @wackazong , will take a look later today.

**Comment by rmk135** [comment]
> When my resource provider causes an exception here, it is leaked to ASGI and not handled correcly

I'm not sure I got it: `it is leaked to ASGI and not handled correctly`. Could you describe what do you mean?

I deployed clean `FastAPI` application with endpoint that always raises an exception. Traceback looks the same:
```
example_1  | INFO:     172.23.0.1:58018 - "GET / HTTP/1.1" 500 Internal Server Error
example_1  | ERROR:    Exception in ASGI application
example_1  | Traceback (most recent call last):
example_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
example_1  |     result = await app(self.scope, self.receive, self.send)
example_1  |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
example_1  |     return await self.app(scope, receive, send)
example_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
example_1  |     await super().__call__(scope, receive, send)
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
example_1  |     await self.middleware_stack(scope, receive, send)
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
example_1  |     raise exc from None
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
example_1  |     await self.app(scope, receive, _send)
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
example_1  |     raise exc from None
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
example_1  |     await self.app(scope, receive, sender)
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
example_1  |     await route.handle(scope, receive, send)
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
example_1  |     await self.app(scope, receive, send)
example_1  |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
example_1  |     response = await func(request)
example_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 201, in app
example_1  |     raw_response = await run_endpoint_function(
example_1  |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
example_1  |     return await dependant.call(**values)
example_1  |   File "./fastapiredis/application.py", line 18, in index
example_1  |     raise Exception()
example_1  | Exception
```

**Comment by wackazong** [comment]
Sorry for being unclear. What I mean is: the exception is not caught by the
exception handlers of FastAPI or my code. If I throw an exception in a
FastAPI router I get a nice JSON response from FastAPI and no full stack
trace in the log (because the exception is handled). Here, the stack trace
appears in the log and I get a text response "Internal Server Error" (and
my exception handler implemented in FastAPI is not called). Would be cool
to handle this exception in a way that it is handled by the FastAPI
exception handlers. Does that make sense?

**Comment by rmk135** [comment]
Alright, it clarifies the situation. I'm wasn't familiar with FastAPI error handler, but I'll get to know how that works. Thanks for explanation.

**Comment by rmk135** [comment]
@wackazong ,

I created such sample code:

```python
import sys

from aioredis import create_redis_pool, Redis
from fastapi import FastAPI, Depends
from dependency_injector import containers, providers
from dependency_injector.wiring import inject, Provide


async def init_redis(url: str):
    pool = await create_redis_pool(url)
    yield pool
    pool.close()
    await pool.wait_closed()


class Container(containers.DeclarativeContainer):

    redis = providers.Resource(init_redis, url='redis://redis')


app = FastAPI()


@app.api_route('/di')
@inject
async def with_id(redis: Redis = Depends(Provide[Container.redis])):
    result = await redis.get('key')
    return {'result': result}


@app.api_route('/no-di')
async def without_di():
    redis_init = init_redis('redis://redis')
    redis = await redis_init.__anext__()
    result = await redis.get('key')
    return {'result': result}


container = Container()
container.wire(modules=[sys.modules[__name__]])
```

There are two endpoints: with and without dependency injector. Both produce same traceback:

```
INFO:     127.0.0.1:60511 - "GET /di HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/src/dependency_injector/wiring.py", line 620, in _patched
    async_to_inject = await asyncio.gather(*[provide for _, provide in to_inject_await])
  File "src/dependency_injector/providers.pyx", line 3539, in dependency_injector.providers.Resource._async_init_callback
  File "./example3.py", line 10, in init_redis
    pool = await create_redis_pool(url)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/commands/__init__.py", line 188, in create_redis_pool
    pool = await create_pool(address, db=db,
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
    transport, _ = await get_event_loop().create_connection(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known


INFO:     127.0.0.1:60513 - "GET /no-di HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "./example3.py", line 34, in index
    redis = await redis_init.__anext__()
  File "./example3.py", line 10, in init_redis
    pool = await create_redis_pool(url)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/commands/__init__.py", line 188, in create_redis_pool
    pool = await create_pool(address, db=db,
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/pool.py", line 58, in create_pool
    await pool._fill_free(override_min=False)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/pool.py", line 383, in _fill_free
    conn = await self._create_new_connection(self._address)
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/connection.py", line 111, in create_connection
    reader, writer = await asyncio.wait_for(open_connection(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/Users/rmoh/projects/ets-labs/python-dependency-injector/venv/lib/python3.9/site-packages/aioredis/stream.py", line 23, in open_connection
    transport, _ = await get_event_loop().create_connection(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1017, in create_connection
    infos = await self._ensure_resolved(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1396, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.1_4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

Seems like the exceptions are handled the same way by FastAPI. Dependency Injector doesn't cause any degradation.

**Comment by rmk135** [comment]
If you'd like to handle all exception and return json you need to install custom FastAPI exception handler:

```python
from fastapi import FastAPI, Depends, Request
from fastapi.responses import JSONResponse


app = FastAPI()


@app.exception_handler(Exception)
async def unicorn_exception_handler(request: Request, exc: Exception):
    return JSONResponse(
        status_code=503,
        content={"message": f"Oops! {exc} did something. There goes a rainbow..."},
    )
```

PS: this is not a Dependency Injector feature, it's FastAPI stuff. See: https://fastapi.tiangolo.com/tutorial/handling-errors/#install-custom-exception-handlers

**Comment by wackazong** [comment]
Thanks for going into the detail here. Ok, let me verify this on my side.

**Comment by wackazong** [comment]
I can confirm this 100%. Thanks!

**Comment by rmk135** [comment]
Good, thanks @wackazong .
