### ISSUE TITLE
AsyncResource integration with fastapi-utils CBVs

### ISSUE THREAD

**Issue by Daveography** [ets-labs/python-dependency-injector#486]
Hello,

I'm trying to use an AsyncResource (to manage SQLAlchemy AsyncSessions) with FastAPI Class-Based Views (from [fastapi-utils](https://fastapi-utils.davidmontague.xyz/user-guide/class-based-views/)) so that I can inject common resources using a base class that my endpoints will inherit. Unfortunately, I can't seem to find a way to make it work.

Not even sure if what I'm wanting to do is possible, but maybe another set of eyes can help.

Here's a rough simplification of my code:

async_session_resource.py:
```python
from dependency_injector import resources
from sqlalchemy.ext.asyncio import AsyncSession

class AsyncSessionProvider(resources.AsyncResource):
    async def init(self, sessionmaker) -> AsyncSession:
        return sessionmaker()

    async def shutdown(self, session: AsyncSession) -> None:
        await session.close()
```

api_container.py:
```python
from async_session_provider import AsyncSessionProvider
from dependency_injector import containers, providers
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

class ApiContainer(containers.DeclarativeContainer):
    config = providers.Configuration()
    config.db_url.from_env("DB_URL")

    engine = providers.Singleton(create_async_engine, url=config.db_url)

    async_session_factory = providers.Singleton(
        sessionmaker,
        bind=engine,
        autoflush=True,
        expire_on_commit=False,
        class_=AsyncSession
    )

    session = providers.Resource(AsyncSessionProvider, async_session_factory)
```

endpoint_base.py:
```python
from api_container import ApiContainer
from dependency_injector.wiring import Closing, Provide, inject
from fastapi.param_functions import Depends

class Endpoint:
    @inject
    def __init__(
        self,
        session: AsyncSession = Depends(Closing[Provide[ApiContainer.session]])
    ):
        self.session = session
```

my_endpoint.py:
```python
from api_router import router # router = APIRouter()
from endpoint_base import Endpoint
from fastapi import Path
from fastapi_utils.cbv import cbv
from my_resource import MyResource

@cbv(router)
class MyEndpoint(Endpoint):
    @router.get("/my/{id}", response_model=MyResource)
    async def get(self, id: int = Path(...)):
        return await self.session.get(MyResource, id)
```

api_app.py:
```python
import sys
import endpoint_base
import my_endpoint
from api_container import ApiContainer
from api_router import router
from dependency_injector.wiring import Provide, inject
from fastapi import FastAPI

class MyAPI(FastAPI):
    def __init__(self):
        super().__init__(on_startup=[self.__load_container])

    def __load_container(self):
        modules = [
            sys.modules[__name__],
            endpoint_base,
            my_endpoint,
        ]

        self.container = ApiContainer()
        self.container.wire(modules=modules)

app = MyAPI()
```

Run:
```bash
uvicorn api_app:app
```

The exception I get when I hit the endpoint:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File ".venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File ".venv\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File ".venv\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".venv\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File ".venv\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File ".venv\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File ".venv\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File ".venv\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File ".venv\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File ".venv\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File ".venv\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File ".venv\lib\site-packages\fastapi\routing.py", line 213, in app
    dependency_overrides_provider=dependency_overrides_provider,
  File ".venv\lib\site-packages\fastapi\dependencies\utils.py", line 552, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File ".venv\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File ".pyenv\pyenv-win\versions\3.7.9\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".venv\lib\site-packages\fastapi_utils\cbv.py", line 82, in new_init
    old_init(self, *args, **kwargs)
  File ".venv\lib\site-packages\dependency_injector\wiring.py", line 595, in _patched
    to_inject[injection] = provider()
  File "src/dependency_injector/providers.pyx", line 207, in dependency_injector.providers.Provider.__call__
  File "src/dependency_injector/providers.pyx", line 3616, in dependency_injector.providers.Resource._provide
  File "src/dependency_injector/providers.pyx", line 3674, in dependency_injector.providers.Resource._create_init_future
  File ".pyenv\pyenv-win\versions\3.7.9\lib\asyncio\tasks.py", line 607, in ensure_future
    loop = events.get_event_loop()
  File ".pyenv\pyenv-win\versions\3.7.9\lib\asyncio\events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

Notes:
- Synchronous `resources.Resource` resources inject properly in `Endpoint.__init__()`
  - I could not find a way to call `session.close()` on an AsyncSession in a synchronous Resource that actually properly closes the session
- Using `async def __init__()` does not result in the above error, but of course I can't set object properties via an async method
- Injecting directly into the async `get()` methods works as expected of course

Is what I'm trying to with CBVs even possible? Am I trying to be too clever?

Thanks!

**Comment by rmk135** [comment]
Hey @Daveography ,

I don't see any possibility to make it work that way. At least I tried and didn't get any good ideas. The thing is that we're trying to make an async injection into``__init__`` method that is never awaited. It's even can't not be async at the moment (Python 3.9). Also using ``Closing`` on ``__init__`` seems erroneous because resource will be closed when ``__init__`` is executed, but not when the object will be destroyed.

The only solution I see is to just inject into view itself:
```python
@cbv(router)
class MyEndpoint(Endpoint):

    @router.get("/my/{id}", response_model=MyResource)
    @inject
    async def get(
            self,
            id: int = Path(...),
            session: AsyncSession = Depends(Closing[Provide[ApiContainer.session]]),
    ):
        return await session.get(MyResource, id)
```

PS: I love the idea. You should be good making this in sync mode btw. However, comment about using ``Closing`` is still relevant.

**Comment by rmk135** [comment]
Hm, I, actually, have an idea... How is about that:

```python
from dependency_injector.providers import Factory


class Endpoint:

    @inject
    def __init__(
            self,
            session_factory: Factory[AsyncSession] = Depends(Provide[ApiContainer.async_session_factory])
    ):
        self.session_factory = session_factory


@cbv(router)
class MyEndpoint(Endpoint):

    @router.get("/my/{id}", response_model=MyResource)
    async def get(self, id: int = Path(...)):
        async with self.session_factory() as session:
            return await session.get(MyResource, id)
```

**Comment by Daveography** [comment]
@rmk135 Great suggestion, thank you! It's not exactly what I was hoping to achieve, but it seems to be about as close as I'm going to get, and it certainly clears up the issues I'm trying to fix.

I appreciate your work on this library, and appreciate even more your quick reply and overall attention to helping out and supporting its users.

**Comment by rmk135** [comment]
You're very welcome. Please, let me know if you need anything else. Cheers!
