### ISSUE TITLE
AttributeError: 'Provide' object has no attribute (FastAPI)

### ISSUE THREAD

**Issue by ricardo17coelho** [ets-labs/python-dependency-injector#521]
i trying to create an app with DI.
Example:  [Application example (multiple containers)](https://python-dependency-injector.ets-labs.org/examples/application-multiple-containers.html)

fastapi==0.70.0
dependency-injector==4.36.2

I got this error when the service is called:
Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/dist-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/dist-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.7/dist-packages/anyio/to_thread.py", line 29, in run_sync
    limiter=limiter)
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.7/dist-packages/anyio/_backends/_asyncio.py", line 743, in run
    result = func(*args)
  File "/usr/local/lib/python3.7/dist-packages/dependency_injector/wiring.py", line 605, in _patched
    result = fn(*args, **to_inject)
  File "./app/api/v1/users.py", line 23, in get_all
    users = service_user.get_all()
AttributeError: 'Provide' object has no attribute 'get_all'
```

containers.py

```
from dependency_injector import containers, providers

from app import redis
from app.services import userservice, sampleservice
import logging.config

class Core(containers.DeclarativeContainer):

    config = providers.Configuration()

    logging = providers.Resource(
        logging.config.dictConfig,
        config=config.logging,
    )


class Gateways(containers.DeclarativeContainer):

    config = providers.Configuration()

    redis_client = providers.Resource(
        redis.init_redis_client,
        host=config.redis.host,
        port=config.redis.port
    )


class Services(containers.DeclarativeContainer):

    config = providers.Configuration()
    gateways = providers.DependenciesContainer()

    sampleservice = providers.Factory(
        sampleservice.Service,
        redis=gateways.redis_client,
    )

    user = providers.Factory(
        userservice.Service,
        redis=gateways.redis_client,
    )


class Application(containers.DeclarativeContainer):

    config = providers.Configuration()

    core = providers.Container(
        Core,
        config=config.core,
    )

    gateways = providers.Container(
        Gateways,
        config=config.gateways,
    )

    services = providers.Container(
        Services,
        config=config.services,
        gateways=gateways
    )

```
userservice.py
```
from aioredis import Redis

class Service:
    def __init__(self, redis: Redis) -> None:
        self._redis = redis

    def get_all(self) :
        return []
```
routes
```
from typing import List
from fastapi import APIRouter, Depends
from dependency_injector.wiring import inject, Provide
from app.containers import Application
from app.services import userservice
from app.models import usermodels

router = APIRouter()


@router.get(
    "/",
    response_model=List[usermodels.UserRead],
)
@inject
def get_all(
    service_user: userservice.Service = Depends(
        Provide[Application.services.user]),
):
    """
    Retrieve details about a all users.
    """
    users = service_user.get_all()
    print("users", users)

    return users

```

main.py
```
import sys

from fastapi import FastAPI, Depends
from starlette.middleware.cors import CORSMiddleware
from dependency_injector.wiring import inject, Provide
from app.containers import Application
import config
from app.api.v1 import api_router


def create_app() -> FastAPI:
    container = Application()
    container.config.from_yaml('config.yml')
    container.wire(modules=[sys.modules[__name__]])

    app = FastAPI()
    app.add_middleware(
        CORSMiddleware,
        allow_origins=config.ALLOWED_HOSTS,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )
    app.container = container
    app.include_router(api_router)
    return app


app = create_app()

```

What i'm doing wrong ?

**Comment by rmk135** [comment]
@ricardo17coelho apologies for the delay. This looks like a bug in the Dependency Injector. I will take a look.

PS: Also, I noticed that you don't have `__init__.py` files in the `enums` and `models` packages. This is, probably, not related to the current issue, just FYI

**Comment by rmk135** [comment]
@ricardo17coelho I wasn't able to reproduce the issue.

**Question:** when you call ``container.wire(modules=[api_router])``, are you sure that ``api_router`` is a module?

I'm asking because the only way I was able to reproduce the issue was to pass router instance instead of module ``container.wire(modules=[APIRouter()])``. If you do the same, change it to pass the module with endpoints to the ``.wire()``.

**Comment by ricardo17coelho** [comment]
@rmk135 Thank you!
I already addet the missing `__init__.py` files.
`container.wire(modules=[api_router])` -> api_router is an instance from APIRouter().

i import `api_router` from `routes.py` (see code from routes above) because i need it for FastApi() 
-> `app.include_router(api_router)`

How can I import it as a module?
Something like:
`import app.api.v1 as router`

**Comment by rmk135** [comment]
Hey @ricardo17coelho ,

I released a feature where you can provide module and package names as a string to ``container.wire()``. In that case, Dependency Injector will make all imports and wiring by its own, nothing extra is needed from your side. So, that are two things I recommend:

1) Use ``container.wire(packages=["app.api.v1"])``, no need to make any imports
2) Use ``APIRouter`` as you need (you initial option should be good)

Hope that helps. Please, let me know if you face any issues.

Best,
Roman

**Comment by ricardo17coelho** [comment]
Hi @rmk135 Thank you,
With:
`container.wire(packages=["app.api.v1"])`
I get this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 36, in <module>
    app = create_app()
  File "./main.py", line 19, in create_app
    container.wire(packages=["app.api.v1"])
  File "src/dependency_injector/containers.pyx", line 256, in dependency_injector.containers.DynamicContainer.wire
  File "/usr/local/lib/python3.7/dist-packages/dependency_injector/wiring.py", line 360, in wire
    for patched in _patched_registry.get_callables_from_module(module):
  File "/usr/local/lib/python3.7/dist-packages/dependency_injector/wiring.py", line 97, in get_callables_from_module
    if patched.__module__ != module.__name__:
AttributeError: 'str' object has no attribute '__name__'
```

**Comment by ricardo17coelho** [comment]
@rmk135  did you receive my email?

**Comment by rmk135** [comment]
@ricardo17coelho , please check if you're using the latest version (``4.37.0``)

**Comment by ricardo17coelho** [comment]
> @ricardo17coelho , please check if you're using the latest version (`4.37.0`)
Hi @rmk135 . Thank you.

It works now.
But i think that the error (or one of them) was that "async" word was missing on the route methode declaration.

Works:
```
@router.get("/test/get_all")
@inject
async def test_get_all(service_sample: sampleservice.Service = Depends(Provide[Application.services.sampleservice])):
    value = service_sample.get_all()
    return {"result": value}
```

Doesn't work:
```
@router.get("/test/get_all")
@inject
def test_get_all(service_sample: sampleservice.Service = Depends(Provide[Application.services.sampleservice])):
    value = service_sample.get_all()
    return {"result": value}
```

**Comment by rmk135** [comment]
> It works now.

Good, I think the last issue was related to the version.

> But i think that the error (or one of them) was that "async" word was missing on the route methode declaration.

I tested wiring with both examples and wasn't able to reproduce the error. I'll close that issue, but feel free to comment if needed.
