### ISSUE TITLE
Using dependency-injector with celery 

### ISSUE THREAD

**Issue by swimmwatch** [ets-labs/python-dependency-injector#559]
Hello! I have some problem with using `dependency-injector` with `celery`.
Celery app:
```python
from celery import Celery
from dependency_injector.wiring import Provide, inject
from redis.client import Redis

from app.config.env import BACKEND_URL, BROKER_URL
from app.containers import Container
from parser import get_mai_structure

celery = Celery(
    backend=BACKEND_URL,
    broker=BROKER_URL
)


@celery.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    sender.add_periodic_task(5.0, update_mai_structure)


@celery.task
@inject
def update_mai_structure(
        redis_client: Redis = Provide[Container.redis_client]):
    """
    Updates MAI structures in Redis store.
    """
    structure = get_mai_structure()
    redis_client.set('mai_structure', structure.json())
```
My DI container:
```python
"""
DI Containers.
"""
from dependency_injector.containers import DeclarativeContainer
from dependency_injector.wiring import providers
from redis import Redis

from app.config.env import REDIS_HOST, REDIS_PORT


class Container(DeclarativeContainer):
    redis_client = providers.Singleton(
        Redis,
        host=REDIS_HOST,
        port=REDIS_PORT
    )
```
Run command:
```bash
celery -A app.celery_tasks worker -B
```
Output:
```bash
(mai-schedule-export-to-ics-thVAUAqi-py3.8) dmitry-vasiliev@xiaomi-mi-air:~/PycharmProjects/mai-schedule-export-to-ics$ celery -A app.celery_tasks worker -B
 
 -------------- celery@xiaomi-mi-air v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.13.0-28-generic-x86_64-with-glibc2.29 2022-02-11 11:50:10
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         __main__:0x7f32cfc4b340
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost/
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[2022-02-11 11:50:12,145: ERROR/ForkPoolWorker-8] Task app.celery_tasks.update_mai_structure[4a64fbc9-dfa8-4e34-b52d-efd1de25bcac] raised unexpected: AttributeError("'Provide' object has no attribute 'set'")
Traceback (most recent call last):
  File "/home/dmitry-vasiliev/.cache/pypoetry/virtualenvs/mai-schedule-export-to-ics-thVAUAqi-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/dmitry-vasiliev/.cache/pypoetry/virtualenvs/mai-schedule-export-to-ics-thVAUAqi-py3.8/lib/python3.8/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/dmitry-vasiliev/.cache/pypoetry/virtualenvs/mai-schedule-export-to-ics-thVAUAqi-py3.8/lib/python3.8/site-packages/dependency_injector/wiring.py", line 612, in _patched
    result = fn(*args, **to_inject)
  File "/home/dmitry-vasiliev/PycharmProjects/mai-schedule-export-to-ics/app/celery_tasks.py", line 28, in update_mai_structure
    redis_client.set('mai_structure', structure.json())
AttributeError: 'Provide' object has no attribute 'set'
^C
worker: Hitting Ctrl+C again will terminate all running tasks!

worker: Warm shutdown (MainProcess)
```
Can someone say how properly to use `dependency-injector` with `celery`?

**Comment by xkortex** [comment]
Looks like maybe the Wiring API/`@inject` does not play nicely with `@celery.task` at this time. You can work around this by using the `Provider` to get the client, it's only one extra step. 

```
@celery.task
def update_mai_structure(
        redis_provider: Provide[Container.redis_client] = Provide[Container.redis_client],
):
    """
    Updates MAI structures in Redis store.
    """
    redis_client = redis_provider.provider()
    log.debug(f"{type(redis_provider)=}")
    log.debug(f"{type(redis_client)=}")
    structure = get_mai_structure()
    redis_client.set('mai_structure', structure.json())
```

```
di_test.app:update_mai_structure:39 - type(redis_provider)=<class 'dependency_injector.wiring.Provide'>
di_test.app:update_mai_structure:40 - type(redis_client)=<class 'redis.client.Redis'>
```

I'm still pretty new to this particular library so there might be a way to get around this using the Wiring pattern, but I was not able to get `@inject` to get the actual provided object.

**Comment by xkortex** [comment]
Aha! I think you may have forgotten `container.wire`. 

> To use wiring you need:
    Place @inject decorator. Decorator @inject injects the dependencies.
    Place markers. Wiring marker specifies what dependency to inject, e.g. Provide[Container.bar]. This helps container to find the injections.
    Wire the container with the markers in the code. Call container.wire() specifying modules and packages you would like to wire it with.
    Use functions and classes as you normally do. Framework will provide specified injections.


Try this: 
```
@celery.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    log.info('periodic')
    container = Container()
    container.wire(modules=[__name__])  # don't forget to wire the container, or else DI lookup fails
    sender.add_periodic_task(5.0, update_mai_structure)


@celery.task
@inject
def update_mai_structure(
        redis_client: Redis = Provide(Container.redis_client),
):
    """
    Updates MAI structures in Redis store.
    """
    log.debug(f"{type(redis_client)=}")
    structure = get_mai_structure()
    redis_client.set('mai_structure', structure.json())
```    

```
di_test.app:update_mai_structure:41 - type(redis_client)=<class 'redis.client.Redis'>
```

**Comment by swimmwatch** [comment]
@xkortex, Yes, it helped. Thank you.
