### ISSUE TITLE
container.init_resources() is not awaitable; it's None

### ISSUE THREAD

**Issue by skewty** [ets-labs/python-dependency-injector#566]
Python 3.9 on Windows 10 system.

```
Traceback (most recent call last):
  File "C:\proj\grandstream-spectralink\src\__main__.py", line 17, in <module>
    asyncio.run(run())
  File "C:\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\proj\grandstream-spectralink\src\__main__.py", line 10, in run
    await container.init_resources()
TypeError: object NoneType can't be used in 'await' expression

Process finished with exit code 1
```

```py
async def run():
    container = Container()
    await container.init_resources()
    try:
        await container.service()
    finally:
        await container.shutdown_resources()


asyncio.run(run())
```

```py
class Container(containers.DeclarativeContainer):
    msg_queue = providers.Singleton(
        asyncio.Queue,
        maxsize=10,
    )
```

also tried this variation thinking it may not recognize the async Queue as needing an event loop:

```py
async def async_create_queue(*args, **kwargs):
    return asyncio.Queue(*args, **kwargs)

class Container(containers.DeclarativeContainer):
    msg_queue = providers.Singleton(
        async_create_queue,
        maxsize=10,
    )
```

What's the trick to get `container.init_resources()` to not return `None`?

**Comment by skewty** [comment]
I thought I worked around the problem above by doing:

```py
async def async_init(container) -> None:
    container.msg_queue()

async def run():
    await async_init(container)
    tasks = [
        asyncio.create_task(container.mqtt_input().run()),
        asyncio.create_task(container.spectralink_output().run()),
    ]
    await asyncio.wait(tasks, return_when=asyncio.ALL_COMPLETED)
    
container = Container()
container.init_resources()
try:
    asyncio.run(run())
except KeyboardInterrupt:
    pass
finally:
    container.shutdown_resources()    
``` 

Both `container.mqtt_input` and `container.spectralink_output` are `providers.Singleton`. They both share the queue created above. The queue wasn't working during testing so I set a breakpoint inside `run()` above and in console I tried this:

```py
>>> container.mqtt_input().queue is container.spectralink_output().queue
False
```

Now, how can that be when all three are supposed to be singleton?

Here is a more complete picture of my container in case it helps:

```py
async def async_init(container) -> None:
    container.msg_queue()
    container.stop_event()
    
class Container(containers.DeclarativeContainer):
    # some resources and configuration removed
    msg_queue = providers.Singleton(asyncio.Queue, maxsize=100)
    stop_event = providers.Singleton(asyncio.Event)
    spectralink_output = providers.Singleton(
        SpectralinkOutput,
        grandstream_config,
        msg_queue,
        stop_event,
        logger,
    )
    mqtt_input = providers.Singleton(
        MqttInput,
        mqtt_config,
        msg_queue,
        stop_event,
        logger,
    )
```

It would seem `providers.Singleton` doesn't provide singleton functionality at all and acts as a factory.

**Comment by rmk135** [comment]
Hi @skewty ,

Please use ``providers.Resource`` instead of ``providers.Singleton``. Method ``container. init_resources`` inits only resource providers.

**Comment by skewty** [comment]
Thanks for the correction.  I switched them to Resource as per your suggestion but I still can't `await container.init_resources()` (it is still None).  Is the type hint just wrong?  How do I get `container.init_resources()` to be awaitable?

**Comment by pawelrubin** [comment]
Hi @skewty. Try to use `providers.AsyncResource` instead. Hope that helps.

**Comment by rmk135** [comment]
Hi @skewty ,

Could you provide a code sample for debugging?

**Comment by kjagiello** [comment]
You forgot to use the `Resource` provider.

```python
import asyncio
from dependency_injector import containers, providers

async def async_function():
    await asyncio.sleep(0)
    yield your_resource

class Container(containers.DeclarativeContainer):
    foo = providers.Resource(async_function())

async def main():
    container = Container()
    await container.init_resources()
    await container.shutdown_resources()

asyncio.run(main())
```

See the documentation and the examples [here](https://python-dependency-injector.ets-labs.org/providers/resource.html#asynchronous-initializers).
