### ISSUE TITLE
Cannot install on windows machine

### ISSUE THREAD

**Issue by Mowinski** [ets-labs/python-dependency-injector#649]
### What happened?

Durring installation, pip raises the exception with encoding. This exception is almost the same as in: https://github.com/ets-labs/python-dependency-injector/issues/643 but I have a problem with cp1250 encoding.  I am using poetry to install dependencies.

```
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing dependency-injector (4.40.0)

  CalledProcessError

  Command 'C:\Users\KMowinski\AppData\Local\pypoetry\Cache\virtualenvs\cyberbieg-validator-dVobx4py-py3.11\Scripts\
python.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\KMowinski\AppData\Local\pypoet
ry\Cache\virtualenvs\cyberbieg-validator-dVobx4py-py3.11 --no-deps C:\Users\KMowinski\AppData\Local\pypoetry\Cache\
artifacts\65\38\8b\a357c3dc165ece634599a0a94beadbc26874aadaa5283a0734a2c7109d\dependency-injector-4.40.0.tar.gz' returned non-zero exit status 1.

  at ~\AppData\Local\Programs\Python\Python311\Lib\subprocess.py:569 in run
       565│             # We don't call process.wait() as .__exit__ does that for us.
       566│             raise
       567│         retcode = process.poll()
       568│         if check and retcode:
    →  569│             raise CalledProcessError(retcode, process.args,
       570│                                      output=stdout, stderr=stderr)
       571│     return CompletedProcess(process.args, retcode, stdout, stderr)
       572│
       573│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command C:\Users\KMowinski\AppData\Local\pypoetry\Cache\virtualenvs\cyberbieg-validator-dVobx4py-py3.11\Scripts\p
ython.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\KMowinski\AppData\Local\pypoetr
y\Cache\virtualenvs\cyberbieg-validator-dVobx4py-py3.11 --no-deps C:\Users\KMowinski\AppData\Local\pypoetry\Cache\a
rtifacts\65\38\8b\a357c3dc165ece634599a0a94beadbc26874aadaa5283a0734a2c7109d\dependency-injector-4.40.0.tar.gz errored with the following return code 1, and output:
  Processing c:\users\kmowinski\appdata\local\pypoetry\cache\artifacts\65\38\8b\a357c3dc165ece634599a0a94beadbc26874aadaa5283a0734a2c7109d\dependency-injector-4.40.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    Getting requirements to build wheel did not run successfully.
    exit code: 1

    [24 lines of output]
    Traceback (most recent call last):
      File "C:\Users\KMowinski\AppData\Local\pypoetry\Cache\virtualenvs\cyberbieg-validator-dVobx4py-py3.11\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
        main()
      File "C:\Users\KMowinski\AppData\Local\pypoetry\Cache\virtualenvs\cyberbieg-validator-dVobx4py-py3.11\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\KMowinski\AppData\Local\pypoetry\Cache\virtualenvs\cyberbieg-validator-dVobx4py-py3.11\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
               ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\KMowinski\AppData\Local\Temp\pip-build-env-jneyc5dp\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\KMowinski\AppData\Local\Temp\pip-build-env-jneyc5dp\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
        self.run_setup()
      File "C:\Users\KMowinski\AppData\Local\Temp\pip-build-env-jneyc5dp\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
        self).run_setup(setup_script=setup_script)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\KMowinski\AppData\Local\Temp\pip-build-env-jneyc5dp\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 15, in <module>
      File "C:\Users\KMowinski\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 8667: character maps to <undefined>     
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  PoetryException

  Failed to install C:/Users/KMowinski/AppData/Local/pypoetry/Cache/artifacts/65/38/8b/a357c3dc165ece634599a0a94beadbc26874aadaa5283a0734a2c7109d/dependency-injector-4.40.0.tar.gz

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\utils\pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│
```

### Contact Details

kamil.mowinski@vulpesoft.pl

**Comment by Mowinski** [comment]
https://github.com/ets-labs/python-dependency-injector/pull/635 Duplicated :) 
I close, because on 4.41 there is no issue. 
Maybe could you cherry pick this fixing to 4.40?

**Comment by rmk135** [comment]
@Mowinski releases on PyPI are immutable. 4.40.0 will remain as is. Please upgrade to 4.41.
