### ISSUE TITLE
Broken wiring of sync inject-decorated methods

### ISSUE THREAD

**Issue by martlaf** [ets-labs/python-dependency-injector#672]
Hi,

following use case seems broken in versions >= 4.39.0:
```python
from dependency_injector import containers, providers
from dependency_injector.wiring import inject, Provide


class Service:
    @staticmethod
    def run():
        print("hello world!")


class Container(containers.DeclarativeContainer):
    service = providers.Factory(Service)


class MyClass:
    @inject
    def __init__(self, service=Provide[Container.service]):
        service.run()


container = Container()
container.wire(modules=[MyClass])
MyClass()
```
Output in version 4.38.0:
```
hello world!
```
Output in versions >4.38.0
```
Traceback (most recent call last):
  File "C:\Users\myself\file.py", line 23, in <module>
    MyClass()
  File "src/dependency_injector/_cwiring.pyx", line 28, in dependency_injector._cwiring._get_sync_patched._patched
  File "C:\Users\myself\file.py", line 18, in __init__
    service.run()
AttributeError: 'Provide' object has no attribute 'run'
```

What seem to happen is that since the `_get_sync_patched` decorator has been moved to the cython part of the package, the signature of the `@inject`-decorated func/methods are now cython (`type(MyClass.__init__)` resolves to `cython_function_or_method`), therefore `inspect.isfunction()`/`inspect.ismethod()` resolve to False, and so those functions are never patched during container wiring.

Might be related to [#589](https://github.com/ets-labs/python-dependency-injector/issues/589).

Finally, I have successfully tested [here](https://github.com/ets-labs/python-dependency-injector/pull/673) using the same patch that was applied in 4.39.1 for `_get_async_patched` coroutine that wasn't properly signed from cython coroutine, so creating the `_get_sync_patched` in wiring.py that calls _cwiring's `_sync_inject`, which effectively conserves behavior when running wiring.

**Comment by sgenya** [comment]
@rmk135 Would it be possible to release a fix for this bug in an upcoming release?

**Comment by yakimka** [comment]
Any updates?

**Comment by Astral1020** [comment]
Any updates? I have same issue, For now I just using dependency-injector==4.38.0

**Comment by tsdaemon** [comment]
I have a similar issue. Is there a workaround?

**Comment by ZipFile** [comment]
You're not supposed to pass into `modules` something other than list of module objects or import strings. In the example from OP post, if you do `container.wire(modules=[__name__])` it will work as expected.

But either way, there are "clever" frameworks/libraries that use `isfunction` in a wild, so making functions decorated by `@inject` recognizable by `isfunction` will improve our interoperability.

**Comment by ZipFile** [comment]
Fixed in [v4.46.0](https://github.com/ets-labs/python-dependency-injector/releases/tag/4.46.0) (https://github.com/ets-labs/python-dependency-injector/pull/673).
